// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef window_h
#define window_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Box.H>

class UserInterface {
public:
  UserInterface();
protected:
  Fl_Double_Window *w;
  Fl_Input *titleInput;
  Fl_Input *labelInput;
  Fl_Input *idInput;
  Fl_Button *okBtn;
  Fl_Button *insertBtn;
  Fl_Button *updateBtn;
  Fl_Button *deleteBtn;
  Fl_Button *clearBtn;
  Fl_Box *titleBox;
  Fl_Browser *dataBrowser;
  Fl_Input *fileInput;
  Fl_Button *importBtn;
  Fl_Button *exportBtn;
  Fl_Button *generateBtn;
};
#endif
